### PR TITLE
Retry boot server with new port if Errno::EADDRINUSE

### PR DESCRIPTION
**Pull request by lukaso**
This combines reducing the time between choosing a port and booting the server #2246 with retrying with a new port if booting fails due to a `Errno::EADDRINUSE.

The retry mechanism works when simulating a retry.

### CODE REVIEW

**Comment by twalpole** [comment]
I don't think this will work as expected since it relies on catching exceptions issued in one thread in a different thread.  It also risks leaving orphan threads.

**Comment by lukaso** [comment]
Ruby gets all excepts from a thread on join, so it does work. Here's a bit of code that I used to test that assumption.

```ruby
x = Thread.new do
  raise "Boom"
end

puts 'still going'

x.join

puts "I'm dead"
```

```sh
$ ruby thread.rb
still going
thread.rb:2:in `block in <main>': Boom (RuntimeError)
```

When I forced an exception on server boot on every call (the first time), all the tests passed so I feel confident it works.

**Comment by lukaso** [comment]
@twalpole this now takes the initial port retry and adds retry of the server if that fails for some reason (stops the very small edge case). I'll leave this here for now, while I try the fix you've merged to master to see if the fix worked (might take a few weeks as the error is rare).

As stated above, I've tested where every creation of a server fails the first time, and all tests pass locally, so I believe this change is safe.

**Comment by lukaso** [comment]
Since merging https://github.com/teamcapybara/capybara/pull/2244 the problem has not reoccurred.

**Comment by lukaso** [comment]
The issue has not recurred since https://github.com/teamcapybara/capybara/pull/2244 was merged.

**Pull request closed without merging**
