### PR TITLE
[WIP] Fix flaky tests

### PR DESCRIPTION
**Pull request by volodymyr-mykhailyk**
While working on Apparition gem that is using capybara suite - noticed few test that sometimes fail. 
This PR is an attempt to make those tests more stable. Still work in progress. Will try to describe every scenario and finding.

### CODE REVIEW

**Comment by volodymyr-mykhailyk** [comment]
When executing `should work with Dragula` test as part of the apparition project - noticed that Dragula is initialized after or somewhere in the middle of drag execution. Most common of events for the failed run:
- Drag begins in spec
- Dragula initialized
- Drag ends

Solution: Update element class on Dragula initialization. Do not begin the test until the page is ready

**Comment by volodymyr-mykhailyk** [comment]
When a remote browser (chrome, firefox) is loading the page and
we are trying to get the document body - we encounter an error
that `document.documentElement` is null. Most often this happens
on refreshing the page or when the page is loaded by async JS code.

In order to recover from this - we give more time for the browser to finish the request and get the body again.

Example of error trace:

```
  1) Capybara::Session selenium_firefox_remote #refresh it reposts
     Failure/Error: browser.page_source

     Selenium::WebDriver::Error::JavascriptError:
       TypeError: document.documentElement is null
     # @http://127.0.0.1:42429/form:2:20
     # @http://127.0.0.1:42429/form:3:8
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium_statistics-0.3.0/lib/selenium_statistics/bridge.rb:14:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:305:in `execute_script'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:116:in `page_source'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:160:in `page_source'
     # ./lib/capybara/selenium/driver.rb:87:in `html'
     # ./lib/capybara/session.rb:195:in `html'
     # ./lib/capybara/spec/spec_helper.rb:122:in `extract_results'
     # ./lib/capybara/spec/session/refresh_spec.rb:31:in `block (3 levels) in <top (required)>'
     # ./lib/capybara/spec/session/refresh_spec.rb:28:in `block (2 levels) in <top (required)>'
```

**Comment by volodymyr-mykhailyk** [comment]
@twalpole While there are many things I can try to fix - I'm concerned that my approach could be wrong. Any early suggestions? Anything I can do differently? Should I continue?

**Comment by twalpole** [comment]
The first commit makes sense to me, the second one does not.  In the second case we should be fixing `body` to retry like most other Capybara methods if it fails.

**Comment by volodymyr-mykhailyk** [comment]
Got it. In such a case - the second commit should be moved to the Selenium gem. I will revert it from here.

**Comment by twalpole** [comment]
I think you misunderstood - it should be fixed in the capybara selenium driver  - the test shouldn’t be changed, but it should be fixed in Capybara


-- Thomas

**Comment by volodymyr-mykhailyk** [comment]
> I think you misunderstood - it should be fixed in the capybara selenium driver - the test shouldn’t be changed, but it should be fixed in Capybara
> […](#)
> -- Thomas
> On May 22, 2020, at 12:21 AM, Volodymyr Mykhailyk ***@***.***> wrote: ﻿ Got it. In such a case - the second commit should be moved to the Selenium gem. I will revert it from here. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, thanks. I figured that it should be moved to `Capybara::Selenium::Driver`. Commit is on the way

Now trying to deal with Screenshot Timeout

**Comment by twalpole** [comment]
FYI - I've cherry picked your first commit into master - not sure on the others yet

**Comment by volodymyr-mykhailyk** [comment]
@twalpole Make sense. It is much simpler than my version. Assuming capybara users using standard matches that wait - they will not see this as a problem, even though it does not fix that particular test.

Closing this PR as there is nothing else I can help with right now

**Pull request closed without merging**
