### PR TITLE
Update puma registration for latest master

### PR DESCRIPTION
**Pull request by twalpole**
This is a WIP -- waiting to see what other changes are made to Puma

### CODE REVIEW

**Comment by nateberkopec** [comment]
We're finalizing Puma 6.0, whatever's on Puma master will be what makes it in, so you can finalize this now 👍

**Comment by elalemanyo** [comment]
Using this branch fixes the issues with `Puma::Events.strings` and `Puma::Events.stdio` but I get now another error:
shot2022-10-14 at 10 10 15@2x

**Comment by amiel** [comment]
Without this fix, we're blocked from upgrading puma. Any chance of a release?

Thanks!

**Comment by twalpole** [comment]
@amiel options
1. Use the master branch. It’s not a gem generally used in production so no risk to using an unreleased version
2. Don’t upgrade to puma 6 yet. There are no security issues in latest 5.x and no groundbreaking changes in 6 for 95% of users so what’s the drive to update NOW
3. Fork this repo and release your own gem under a new name
4. Wait until I have time to do a release on my schedule

Pick one, posting on closed issues helps nobody

**Comment by amiel** [comment]
Hi @twalpole. As I re-read my comment, I see how it was perceived as impatience, which I apologize for. I did not intend this, but here we are.

I will for sure wait and look forward to a release that includes this change.

FWIW, I appreciate your time and effort maintaining cabybara, from which I have made use of across many projects over the years. Thank you!

**Comment by twalpole** [comment]
3.38.0 has been released

**Pull request merged**
