### PR TITLE
Tweak Puma server registration for compatibility with Puma 6

### PR DESCRIPTION
**Pull request by elalemanyo**
Inspired by teamcapybara/capybara/issues/2590

### CODE REVIEW

**Comment by MSP-Greg** [comment]
I started on a patch for this, got sidetracked.  See:

https://github.com/MSP-Greg/capybara/commit/48f23ef1e240a39de54c8d976bb2d3ea88f3dd79

Take anything you'd like.  There is additional Puma version checking, showing when min/max threads needs to be set.  I also set min_threads minimum to 1, so a thread is always available...

**Comment by elalemanyo** [comment]
@MSP-Greg Thanks! Yours looks very nice. I improved mine using your ideas. I hope it is fine for you 🙂

**Comment by MSP-Greg** [comment]
> I hope it is fine for you

Yes.

**Comment by twalpole** [comment]
Thanks, but I took the work from https://github.com/teamcapybara/capybara/pull/2530 instead

**Pull request closed without merging**
