### PR TITLE
Cleanup History.md markdown and presentation

### PR DESCRIPTION
**Pull request by roberts1000**
The markdown formatting in `History.md` is messed up.  This PR gets History.md looking awesome again.

### CODE REVIEW

**Comment by twalpole** [comment]
Hmmm -- not sure what happened there - thanks.

**Comment by roberts1000** [comment]
Thanks for merging.  Any interest in renaming History.md to CHANGELOG.md if I submit another PR?  I typically look for a CHANGELOG.md first, when a new version comes out.

**Comment by twalpole** [comment]
@roberts1000 Not really

**Comment by roberts1000** [comment]
Roger.  Thanks for considering.

**Pull request merged**
