### PR TITLE
Test with selenium remote driver

### PR DESCRIPTION
**Pull request by twalpole**
Fix date setting when using remote driver and run CI test with "remote" selenium using Chrome.  Fixes Issue #2018

### CODE REVIEW

**Comment by ianks** [comment]
Oo! Looks like we both had the same idea: https://github.com/teamcapybara/capybara/pull/2020

How would you like to move forward here?

**Comment by twalpole** [comment]
Ok -- if you want to take my changes to lib/capybara/selenium/driver.rb and lib/capybara/selenium/node.rb rather than your changes, we'll go with your docker based PR

**Comment by ianks** [comment]
Ok sounds good. I'll attempt to cherry pick the commits

**Comment by twalpole** [comment]
@ianks - It's just one commit -- just implement them as your own

**Comment by twalpole** [comment]
Closing in favor of PR #2019

**Pull request closed without merging**
