### PR TITLE
Prefer symbol keys.

### PR DESCRIPTION
**Pull request by ioquatix**
Using symbol keys reduces memory usage and improves performance slightly.

### CODE REVIEW

**Comment by twalpole** [comment]
Thanks this is definitely in when we get to 4.0 - prior to that I need to think about whether I consider this a breaking change

**Comment by ioquatix** [comment]
Great.

**Comment by anikettstiwari** [comment]
@ioquatix  Can you share some stats when use symbol over string reduces memory usage

**Comment by pankaj3150** [comment]
can you add more two the regester

**Comment by ioquatix** [comment]
@twalpole also note that `Thread.current[...]` is fiber local, not thread local, if that is what you are expecting.

**Pull request closed without merging**
