### PR TITLE
Disable animations on pseudoelement content as well as regular elements

### PR DESCRIPTION
**Pull request by DanielHeath**
Resolves https://github.com/teamcapybara/capybara/issues/2221

Very hard to add test cases for due to https://github.com/SeleniumHQ/selenium/issues/2517 .

### CODE REVIEW

**Comment by twalpole** [comment]
Because these are referring to pseudo elements (vs pseudo classes) I believe it should be ::before and ::after (double colon)

**Comment by DanielHeath** [comment]
Ahh - https://developer.mozilla.org/en-US/docs/Web/CSS/::before indicates that `::before` is preferred, though both are accepted by browsers.

**Comment by twalpole** [comment]
As for testing - it can probably be done by registering a `transitionend` and `animationend` handler that add something to the page and making sure they don't fire when animations are disabled.  Haven't actually tried that though so it's only "probably"

**Comment by DanielHeath** [comment]
I put a bit of time in to figuring it out; this kind of issue tends to only trigger on more complex layouts. I might be able to make the `:before` content cover the link after it's been clicked, then assert that clicking the link obscures it.

**Comment by twalpole** [comment]
I've added a test for this - so merging now -- thanks!

**Pull request merged**
