### PR TITLE
Reuse also middlewares

### PR DESCRIPTION
**Pull request by abicky**
This PR resolves https://github.com/teamcapybara/capybara/issues/2106.

### CODE REVIEW

**Comment by twalpole** [comment]
Unfortunately this has been tried previously and leads to deadlocks during session reset when one session is waiting but a later session hasn't yet been reset.  Implementing something like this requires reworking reset so that all open sessions get reset before waiting for all sessions pending_requests to end

**Comment by twalpole** [comment]
The real solution to this would be tying all requests in the middleware to a specific session (cookie, query parameter, etc) but I haven't spent the time to work out whether or not that's actually possible with multiple subdomains, etc

**Comment by abicky** [comment]
Umm, how about a change like below? I think `Capybara::Server` shouldn't depend on `Capybara.current_session`, but this is easy solution.

```diff
diff --git a/lib/capybara/server.rb b/lib/capybara/server.rb
index ee57f5c5..8804b155 100644
--- a/lib/capybara/server.rb
+++ b/lib/capybara/server.rb
@@ -55,6 +55,10 @@ module Capybara
     end

     def wait_for_pending_requests
+      if Capybara.current_session.server != self
+        raise "#{__method__} is called but the current session server is another. Please set Capybara.reuse_server to false."
+      end
+
       timer = Capybara::Helpers.timer(expire_in: 60)
       while pending_requests?
         raise 'Requests did not finish in 60 seconds' if timer.expired?
```

If it looks good, I'll fix tests.

**Comment by twalpole** [comment]
That will cause `reset_sessions!` to raise whenever there is more than one session being used

**Comment by abicky** [comment]
I close this PR cf. https://github.com/teamcapybara/capybara/issues/2106

**Pull request closed without merging**
