### PR TITLE
Add docs about Capybara.save_path and #save_screenshot

### PR DESCRIPTION
**Pull request by strika**
Hope this will save few minutes for other developers. Thanks.

### CODE REVIEW

**Comment by twalpole** [comment]
This is only true if you've required capybara/rails and not set anything else.

**Comment by strika** [comment]
I see. Any suggestions how a developer can know where a screenshot is going to be saved? (Without digging into the [code](https://github.com/teamcapybara/capybara/blob/1730fd91e7a7e6c02a9492682c595bceb2448648/lib/capybara/session.rb#L821-L829)).

**Comment by twalpole** [comment]
@strika Rather than saying "If the application that you are testing is a Rails app" say something like "If you have required capybara/rails Capybara.save_path will default to ..."

**Comment by strika** [comment]
Thanks. I updated the PR.

Is it a problem that this doesn't cover all cases (e.g. it doesn't mention `Capybara.save_and_open_page_path`)?

**Comment by twalpole** [comment]
@strika save_and_open_page_path is deprecated so it doesn't matter

**Comment by twalpole** [comment]
Thanks

**Pull request merged**
