### PR TITLE
Added dependabot for GitHub Actions and bundler

### PR DESCRIPTION
**Pull request by ydah**
How about using dependabot in this way?
When this works, a PullRequest is created as follows:
- ruby/bigdecimal#242

It was created with reference to the following:
- ruby/csv#265

### CODE REVIEW

**Comment by mvz** [comment]
How about also enabling it for the gem dependencies?

**Comment by ydah** [comment]
Indeed it is, I believe Gemfile also created a PR for me if I had specified a version limit, but it doesn't seem to be necessary this repository.

**Comment by simi** [comment]
@mvz even for gemspec based constraints? :thinking:

**Comment by mvz** [comment]
@simi yes, I use it for nearly all my gems.

**Comment by twalpole** [comment]
I'm not interested in this right now -- thanks anyway

**Pull request closed without merging**
