### PR TITLE
Support configuring the puma server to use SSL

### PR DESCRIPTION
**Pull request by twalpole**
This supports configuring the puma server to use SSL via setting `Capybara.server` along the lines of 

    Capybara.server = :puma, { Host: "ssl://#{Capybara.server_host}?key=<key_file>&cert=<cert_file>"

It should work with other server types that are configured to run SSL too

### CODE REVIEW

**Comment by skryshi** [comment]
I can verify that Capybara does start puma server in ssl mode, but then it hangs for a long time and eventually errors out with: `Net::ReadTimeout`

My rails_helper.rb:

`Capybara.app_host = "https://www-test.localhost.local:3200"`
`Capybara.asset_host = "https://www-test.localhost.local:3200"`
`Capybara.server_host = "www-test.localhost.local"`
`Capybara.server_port = "3200"`

`Capybara.server = :puma, { Host: "ssl://#{Capybara.server_host}:#{Capybara.server_port}?key=#{ENV['SSL_KEY_PATH']}&cert=#{ENV['SSL_CERT_PATH']}" }`
`Capybara.javascript_driver = :selenium_chrome`

Capybara output:

`Capybara starting Puma...`
`* Version 3.11.4 , codename: Love Song`
`* Min threads: 0, max threads: 4`
`* Listening on ssl://www-test.localhost.local:3200?key=/usr/local/ssl/localhost.key&cert=/usr/local/ssl/localhost.crt`

**Comment by twalpole** [comment]
@skryshi The only real differences I see between your config and what the added test does are 

1.  You're specifying the `server_port` both directly and in the puma Host config (which should be an integer not a string).  Do you have a specific reason for needing to do that?

2.  You're specifying `app_host` which shouldn't be necessary, do you have a specific reason for doing that?

What code location is the `Net::ReadTimeout` error being generated from?

One other issue with your config which shouldn't be affecting this is specifying `asset_host` as the same location as 'app_host' - it kind of defeats the whole purpose of `asset_host`.

**Comment by skryshi** [comment]
No, it wasn't the `verify_mode`. I figured I can specify it with:

> Capybara.server = :puma, { Host: "ssl://#{Capybara.server_host}?key=#{ENV['SSL_KEY_PATH']}&cert=#{ENV['SSL_CERT_PATH']}&verify_mode=none" }

But it still errors out. Now I am out of ideas :(

**Comment by twalpole** [comment]
@skryshi You shouldn't need to set the verify mode for puma -- it would be the browser that might need to be set to ignore cert errors, although you should see an error in the console if that was the case.  From the stacktrace it looks like it could be something to do with webmock and/or  Net::HTTP timeout settings changes.  Are you changing any of the default Net::HTTP timeouts, and can you try disabling/removing WebMock to see if the SSL connects then.

**Comment by twalpole** [comment]
@skryshi I've also added a few extra `puts` to this PR - so if you could update and try again it may give us a better idea of what's going on.

**Comment by skryshi** [comment]
@twalpole Thank you for investing time into this! I get:


> attempting http connection to 127.0.0.1:64942
Got Exception: Errno::ECONNREFUSED
attempting http connection to 127.0.0.1:64942
Got Exception: Errno::ECONNREFUSED
Capybara starting Puma...
> * Version 3.11.4 , codename: Love Song
> * Min threads: 0, max threads: 4
> * Listening on ssl://127.0.0.1:64942?key=/usr/local/ssl/localhost.key&cert=/usr/local/ssl/localhost.crt
attempting http connection to 127.0.0.1:64942
Got Exception: Net::ReadTimeout
attempting http connection to 127.0.0.1:64942
Got Exception: Net::ReadTimeout
F

Seems that Capybara is trying to connect over HTTP. How do I tell it to use HTTPS?

**Comment by twalpole** [comment]
@skryshi in my setup the attempted http connection gets an EOFError which will cause a failover to attempting an https connection.  In your case you’re getting a Net::ReadTimeout which doesn’t currently cause a failover.  I would like to understand why you’re getting that rather than just adding it as another failover error.  Did you try removing webmock? And have you modified any of the Net::HTTP timeouts?

**Comment by skryshi** [comment]
@twalpole I haven't touched Net:HTTP anywhere in my project. Removing webmock gives the same results:

    attempting http connection to 127.0.0.1:52095
    Got Exception: Errno::ECONNREFUSED
    attempting http connection to 127.0.0.1:52095
    Capybara starting Puma...Got Exception: Errno::ECONNREFUSED

    * Version 3.11.4 , codename: Love Song
    * Min threads: 0, max threads: 4
    * Listening on ssl://127.0.0.1:52095?key=/usr/local/ssl/localhost.key&cert=/usr/local/ssl/localhost.crt
    attempting http connection to 127.0.0.1:52095
    Got Exception: Net::ReadTimeout
    F
    Failures:

    1) Email Sign Up with new email 
     Failure/Error: visit new_user_registration_path
     
     Net::ReadTimeout:
       Net::ReadTimeout
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/server.rb:89:in `block in responsive?'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/server.rb:89:in `responsive?'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/server.rb:125:in `boot'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/session.rb:87:in `initialize'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara.rb:298:in `new'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara.rb:298:in `current_session'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/dsl.rb:46:in `page'
     # /Users/arman/.rvm/gems/ruby-2.4.3/bundler/gems/capybara-aac927e53dc0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/authentication_pages_spec.rb:69:in `block (3 levels) in <top (required)>'


I don't think catching Net::ReadTimeout will work, because that timeout happens after several minutes. It would be impossibly slow to run the tests then. Wouldn't it be better to have a setting, eg. `Capybara.use_ssl = true` that I can set in config?

**Comment by twalpole** [comment]
I can set the read timeout for the specific request - so it shouldn't have to wait minutes - but I would really like to know why your setup is raising that error rather than EOFError

**Comment by aliahmed922** [comment]
@twalpole I have pointed my capybara gem to **ssl_support** branch and setup the ssl configuration just like mentioned. I have see many issues over stackoverflow and here as well that it hangs after puma is ready with ssl. But in my case everything works fine except my tests are not getting passed in headless chrome or if I want to go with browser then I gotta focus my window all the time until all specs are done. I want to get rid of this and it was working fine in headless chrome ever since I added ssl support.

Additionally I am using subdomains in my application for which I needed to use lvh.me host. So just set up the configuration:

`Capybara.server_host = 'lvh.me'`
`Capybara.server = :puma, { Host: "ssl://lvh.me:#{Capybara.server_port}?key=certs/localhost.key&cert=certs/localhost.crt" }`

As said everything goes fine but tests are failing, plus I am getting this weird error always

`2018-05-22 14:40:59 +0500: SSL error, peer: 127.0.0.1, peer cert: , #<Puma::MiniSSL::SSLError: OpenSSL error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request - 336027804>`

but I do not get this in development mode. Please provide some help with this.

**Comment by twalpole** [comment]
@aliahmed922 

1. As can be seen from above the PR was merged into master (and then released in version 3.1.0) so you definitely shouldn't be using the `ssl_support` branch anymore.

2.  The Error message is emitted by Puma and is when Capybara attempts an `http` connection before `https` - It's not harmful in any way and can be silenced with the `Silent: true` option to puma if wanted.

3.  You have provided no info whatsoever about your failing tests so there is nothing we can do.

If you have found an actual issue with Capybara please open a new issue with enough information to reproduce the issue, if all you really have is failing tests that are most likely caused by user issues then please ask on the mailing list (as requested in the README) or on stackoverflow  and make sure to provide enough information about the failing tests for someone to be able to diagnose (real code, actual errors, stack trace, etc)

**Pull request merged**
