### PR TITLE
Experimental Rack 3 support

### PR DESCRIPTION
**Pull request by twalpole**
Work in progress

### CODE REVIEW

**Comment by AlexWayfer** [comment]
```
Rack::Handler is deprecated and replaced by Rackup::Handler
Capybara starting Puma...
* Version 6.1.0 , codename: The Way Up
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:38457
F

Failures:

  1) index page 
     Failure/Error: visit '/'
     
     NoMethodError:
       undefined method `positive?' for nil:NilClass
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/selenium_manager.rb:80:in `run'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/selenium_manager.rb:41:in `driver_path'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/service.rb:107:in `binary_path'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/service.rb:74:in `initialize'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/service.rb:36:in `new'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/service.rb:36:in `firefox'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/firefox/driver.rb:43:in `initialize'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/driver.rb:53:in `new'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/driver.rb:53:in `for'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver.rb:88:in `for'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/capybara-f857a99ff069/lib/capybara/selenium/driver.rb:83:in `browser'
     # /home/alex/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/capybara-f857a99ff069/lib/capybara/selenium/driver.rb:104:in `visit'
```

**Comment by twalpole** [comment]
@AlexWayfer what are you trying to say here?

**Comment by MSP-Greg** [comment]
As mentioned - `Rack::Handler is deprecated and replaced by Rackup::Handler`

The next release of Puma will define `Rackup::Handler::Puma` if `Rackup` is defined, and leave the namespace as `Rack::Handler::Puma` if it is not.

**Comment by AlexWayfer** [comment]
> As mentioned - `Rack::Handler` is deprecated and replaced by `Rackup::Handler`

I have nothing about `Handler`.



> The next release of Puma will define `Rackup::Handler::Puma` if `Rackup` is defined, and leave the namespace as `Rack::Handler::Puma` if it is not.

So… I have to wait for next Puma 6.x release?

Or what can I do to make tests working with the latest versions of Capybara and Puma?

**Comment by MSP-Greg** [comment]
> latest versions of Capybara and Puma?

Are you referring to latest versions, as in main/master branch, or latest releases?  Also, are you using Rack 2 or Rack 3?

**Comment by AlexWayfer** [comment]
> > latest versions of Capybara and Puma?
> 
> Are you referring to latest versions, as in main/master branch, or latest releases? Also, are you using Rack 2 or Rack 3?

Releases, I believe.

```
...
  * capybara (3.38.0)
...
  * puma (6.1.0)
...
  * rack (3.0.4.1)
...
  * rackup (2.1.0)
...
```

Rack 3, as you can see.

My code also was using `gem 'capybara', github: 'teamcapybara/capybara'`, I guess because this PR is still not in a stable release, but… the same error.

And, my message was "why there is no a new release of Capybara?".

**Comment by MSP-Greg** [comment]
@AlexWayfer

Thanks. That helps. It's messy, adding in the fact some files were removed from Rack 2 and placed in Rackup.  So, you can try specifying a commit with `gem 'capybara', github: 'teamcapybara/capybara'`.  I think things will also work if you can use Rack 2.  Not sure about either...   I know that turbo-rails runs CI with Capybara 3.38.0, Puma 6.1.0, and Rack 2.x.

**Comment by MSP-Greg** [comment]
@twalpole

Re the current issue, you want to get at `Rack::Handler::Puma.config`, which may be `Rackup::Handler::Puma.config`.  Would it be easier to get at `Puma::RackHandler.config`, and not bother with the Rack/Rackup namespace?  `Puma::RackHandler` contains the methods that are included in `Rack::Handler::Puma` or `Rackup::Handler::Puma`, depending on which is defined.  If `extend self` is added to the module, you can access it directly...

**Comment by AlexWayfer** [comment]
> So, you can try specifying a commit with `gem 'capybara', github: 'teamcapybara/capybara'`.

Which one commit? And what changed in `master`?



> I think things will also work if you can use Rack 2.

I don't understand: I have everything supporting Rack 3, including Capybara `master` with this merged PR.

Yes, it's "experimental". So, do we have an issue and Capybara still not compatible with Rack 3, even in `master` with this PR, or am I doing something wrong?

**Comment by AlexWayfer** [comment]
Should I create a new issue or how should I test my application with Puma and Capybara?

**Pull request merged**
